### PR TITLE
Bridge iOS SDK issue #118

### LINKED ISSUE #118: _SBBResourceList updateManagedObject crash
We are experiencing the crash while using class _SBBResourceList. 
- This crash occurred in ios 9.x after logging in using an existing username for the study identifier "stsi-preganancy"
- Error found in line: 209 in function: updateManagedObject: withObjectManager: cacheManager: 
Please let us know if you need any other information from our end.

Stack Trace:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSOrderedSet isSubsetOfSet:]: set argument is not an NSSet'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d681d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010cc31deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d6cb5cc -[NSOrderedSet isSubsetOfSet:] + 428
	3   Foundation                          0x000000010923d7c7 NSKeyValueWillChangeBySetMutation + 371
	4   Foundation                          0x00000001091b3a3e NSKeyValueWillChange + 383
	5   Foundation                          0x000000010923d5f1 -[NSObject(NSKeyValueObserverNotification) willChangeValueForKey:withSetMutation:usingObjects:] + 557
	6   CoreData                            0x000000010d27da17 _sharedIMPL_removeSet_core + 119
	7   BridgeSDK                           0x000000010c89a8f6 -[_SBBResourceList updateManagedObject:withObjectManager:cacheManager:] + 694
	8   BridgeSDK                           0x000000010c89a4ca -[_SBBResourceList createInContext:withObjectManager:cacheManager:] + 186
	9   BridgeSDK                           0x000000010c8fd9c2 __69-[SBBCacheManager cachedObjectOfType:withId:createIfMissing:created:]_block_invoke + 770
	10  CoreData                            0x000000010d210127 developerSubmittedBlockToNSManagedObjectContextPerform + 199
	11  CoreData                            0x000000010d20ffee -[NSManagedObjectContext performBlockAndWait:] + 222
	12  BridgeSDK                           0x000000010c8fd47e -[SBBCacheManager cachedObjectOfType:withId:createIfMissing:created:] + 990
	13  BridgeSDK                           0x000000010c8fe776 -[SBBCacheManager cachedObjectFromBridgeJSON:createIfMissing:] + 2246
	14  BridgeSDK                           0x000000010c8fde78 -[SBBCacheManager cachedObjectFromBridgeJSON:] + 72
	15  BridgeSDK                           0x000000010c8e1d3e -[SBBObjectManager objectFromBridgeJSON:] + 1390
	16  BridgeSDK                           0x000000010c8c3641 __97-[SBBActivityManager getScheduledActivitiesForDaysAhead:daysBehind:cachingPolicy:withCompletion:]_block_invoke_2 + 289
	17  CoreData                            0x000000010d210127 developerSubmittedBlockToNSManagedObjectContextPerform + 199
	18  libdispatch.dylib                   0x000000010fd963eb _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x000000010fd7c82c _dispatch_queue_drain + 2215
	20  libdispatch.dylib                   0x000000010fd7bd4d _dispatch_queue_invoke + 601
	21  libdispatch.dylib                   0x000000010fd7e996 _dispatch_root_queue_drain + 1420
	22  libdispatch.dylib                   0x000000010fd7e405 _dispatch_worker_thread3 + 111
	23  libsystem_pthread.dylib             0x00000001100d34de _pthread_wqthread + 1129
	24  libsystem_pthread.dylib             0x00000001100d1341 start_wqthread + 13
)

### PR DESCRIPTION
**Pull request by Erin-Mounts**
work around this problem (pre-iOS 10): http://stackoverflow.com/questions/7385439/exception-thrown-in-nsorderedset-generated-accessors. fixes #118

### CODE REVIEW

File: BridgeSDK/mogenerator_ponso_templates/templates/machine.m.motemplate [hunk 1]
```diff
@@ -605,7 +609,11 @@ static id dynamicGetterIMP(id self, SEL _cmd)
                 // sub object is not directly cacheable, or not currently cached, so create it before adding
                 relMo = [obj createInContext:cacheContext withObjectManager:objectManager cacheManager:cacheManager];
             }
+            <$if Relationship.isOrdered$>
+            [working<$Relationship.name.initialCapitalString$>Set addObject:relMo];
+            <$else$>
             [managedObject add<$Relationship.name.initialCapitalString$>Object:relMo];
+            <$endif$>
         }
 	}
```
Comment (syoung-smallwisdom) [inline BridgeSDK/mogenerator_ponso_templates/templates/machine.m.motemplate]: Don't you need to add this?

````
            <$if Relationship.isOrdered$>
            [managedObject set<$Relationship.name.initialCapitalString$>: working<$Relationship.name.initialCapitalString$>Set];
            <$endif$>
````

**Comment by syoung-smallwisdom** [comment]
mutableOrderedSetValueForKey gives read-write access to the underlying relationship: https://developer.apple.com/reference/objectivec/nsobject/1415479-mutableorderedsetvalueforkey

**Comment by syoung-smallwisdom** [comment]
looks good
